//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.UsersWS
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/")]
    public partial class DuplicatedUserNameException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/")]
    public partial class user
    {
        
        private string emailField;
        
        private string fullNameField;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/")]
    public partial class UserNotFoundException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", ConfigurationName="WSClient.UsersWS.UsersWS")]
    public interface UsersWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/getUsersRequest" +
            "", ReplyAction="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/getUsersRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.UsersWS.getUsersResponse> getUsersAsync(WSClient.UsersWS.getUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/addUserRequest", ReplyAction="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/addUserResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSClient.UsersWS.DuplicatedUserNameException), Action="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/addUser/Fault/D" +
            "uplicatedUserNameException", Name="DuplicatedUserNameException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.UsersWS.addUserResponse> addUserAsync(WSClient.UsersWS.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/getUserRequest", ReplyAction="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/getUserResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.UsersWS.getUserResponse> getUserAsync(WSClient.UsersWS.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/updateUserReque" +
            "st", ReplyAction="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/updateUserRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSClient.UsersWS.UserNotFoundException), Action="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/updateUser/Faul" +
            "t/UserNotFoundException", Name="UserNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.UsersWS.updateUserResponse> updateUserAsync(WSClient.UsersWS.updateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/deleteUserReque" +
            "st", ReplyAction="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/deleteUserRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WSClient.UsersWS.UserNotFoundException), Action="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/UsersWS/deleteUser/Faul" +
            "t/UserNotFoundException", Name="UserNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.UsersWS.deleteUserResponse> deleteUserAsync(WSClient.UsersWS.deleteUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsers", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class getUsersRequest
    {
        
        public getUsersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersResponse", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class getUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WSClient.UsersWS.user[] @return;
        
        public getUsersResponse()
        {
        }
        
        public getUsersResponse(WSClient.UsersWS.user[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUser", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class addUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.UsersWS.user arg0;
        
        public addUserRequest()
        {
        }
        
        public addUserRequest(WSClient.UsersWS.user arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUserResponse", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class addUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.UsersWS.user @return;
        
        public addUserResponse()
        {
        }
        
        public addUserResponse(WSClient.UsersWS.user @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUser", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class getUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getUserRequest()
        {
        }
        
        public getUserRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserResponse", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class getUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.UsersWS.user @return;
        
        public getUserResponse()
        {
        }
        
        public getUserResponse(WSClient.UsersWS.user @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUser", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class updateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.UsersWS.user arg0;
        
        public updateUserRequest()
        {
        }
        
        public updateUserRequest(WSClient.UsersWS.user arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUserResponse", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class updateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.UsersWS.user @return;
        
        public updateUserResponse()
        {
        }
        
        public updateUserResponse(WSClient.UsersWS.user @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteUser", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class deleteUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public deleteUserRequest()
        {
        }
        
        public deleteUserRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteUserResponse", WrapperNamespace="http://webservices.usersws.finalpractice.ws.miw.uniovi.es/", IsWrapped=true)]
    public partial class deleteUserResponse
    {
        
        public deleteUserResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface UsersWSChannel : WSClient.UsersWS.UsersWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class UsersWSClient : System.ServiceModel.ClientBase<WSClient.UsersWS.UsersWS>, WSClient.UsersWS.UsersWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UsersWSClient() : 
                base(UsersWSClient.GetDefaultBinding(), UsersWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UsersWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersWSClient(EndpointConfiguration endpointConfiguration) : 
                base(UsersWSClient.GetBindingForEndpoint(endpointConfiguration), UsersWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UsersWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UsersWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.UsersWS.getUsersResponse> WSClient.UsersWS.UsersWS.getUsersAsync(WSClient.UsersWS.getUsersRequest request)
        {
            return base.Channel.getUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.UsersWS.getUsersResponse> getUsersAsync()
        {
            WSClient.UsersWS.getUsersRequest inValue = new WSClient.UsersWS.getUsersRequest();
            return ((WSClient.UsersWS.UsersWS)(this)).getUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.UsersWS.addUserResponse> WSClient.UsersWS.UsersWS.addUserAsync(WSClient.UsersWS.addUserRequest request)
        {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.UsersWS.addUserResponse> addUserAsync(WSClient.UsersWS.user arg0)
        {
            WSClient.UsersWS.addUserRequest inValue = new WSClient.UsersWS.addUserRequest();
            inValue.arg0 = arg0;
            return ((WSClient.UsersWS.UsersWS)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.UsersWS.getUserResponse> WSClient.UsersWS.UsersWS.getUserAsync(WSClient.UsersWS.getUserRequest request)
        {
            return base.Channel.getUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.UsersWS.getUserResponse> getUserAsync(string arg0)
        {
            WSClient.UsersWS.getUserRequest inValue = new WSClient.UsersWS.getUserRequest();
            inValue.arg0 = arg0;
            return ((WSClient.UsersWS.UsersWS)(this)).getUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.UsersWS.updateUserResponse> WSClient.UsersWS.UsersWS.updateUserAsync(WSClient.UsersWS.updateUserRequest request)
        {
            return base.Channel.updateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.UsersWS.updateUserResponse> updateUserAsync(WSClient.UsersWS.user arg0)
        {
            WSClient.UsersWS.updateUserRequest inValue = new WSClient.UsersWS.updateUserRequest();
            inValue.arg0 = arg0;
            return ((WSClient.UsersWS.UsersWS)(this)).updateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.UsersWS.deleteUserResponse> WSClient.UsersWS.UsersWS.deleteUserAsync(WSClient.UsersWS.deleteUserRequest request)
        {
            return base.Channel.deleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.UsersWS.deleteUserResponse> deleteUserAsync(string arg0)
        {
            WSClient.UsersWS.deleteUserRequest inValue = new WSClient.UsersWS.deleteUserRequest();
            inValue.arg0 = arg0;
            return ((WSClient.UsersWS.UsersWS)(this)).deleteUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UsersWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UsersWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://156.35.98.70:8080/ws.finalpractice.usersws/soapws/users");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UsersWSClient.GetBindingForEndpoint(EndpointConfiguration.UsersWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UsersWSClient.GetEndpointAddress(EndpointConfiguration.UsersWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            UsersWSPort,
        }
    }
}
